INSERT INTO tb_usuario (id, nome, cargo, area, matricula, nivel, xp, xp_proximo_nivel, ofensiva_dias, cursos_concluidos, horas_estudo) VALUES (1, 'Marina Ribeiro Costa', 'Analista de Qualidade Pleno', 'Garantia da Qualidade', 'EF204815', 7, 2450, 3000, 12, 2, 47);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (1, 'Boas Práticas de Fabricação (BPF)', 'Regulatório', 'Dra. Helena Vasconcelos', 'Requisitos de BPF aplicados à produção de medicamentos conforme a RDC 658/2022, com foco em controle de contaminação e rastreabilidade documental.', 12, true, '2026-12-15');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (1, 'Fundamentos das Boas Práticas', 1, 1);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (1, 'Marco regulatório e a RDC 658/2022', 22, 'VIDEO', 1, 1);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (2, 'Estrutura documental exigida pela ANVISA', 18, 'LEITURA', 2, 1);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (3, 'Papéis e responsabilidades na planta', 15, 'VIDEO', 3, 1);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (2, 'Controle de contaminação', 2, 1);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (4, 'Contaminação cruzada e áreas segregadas', 25, 'VIDEO', 1, 2);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (5, 'Fluxo de pessoas, materiais e pressão diferencial', 20, 'VIDEO', 2, 2);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (6, 'Avaliação do módulo de contaminação', 12, 'QUIZ', 3, 2);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (3, 'Documentação e auditoria', 3, 1);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (7, 'Registro de lote e revisão por exceção', 24, 'LEITURA', 1, 3);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (8, 'Preparação para auditoria da ANVISA', 30, 'AO_VIVO', 2, 3);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (2, 'Farmacovigilância na Prática', 'Regulatório', 'Dr. Rogério Tanaka', 'Identificação, notificação e análise de eventos adversos, com os prazos regulatórios e o fluxo interno de escalonamento de casos graves.', 10, true, '2026-11-28');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (4, 'Conceitos e marco legal', 1, 2);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (9, 'O que caracteriza um evento adverso', 20, 'VIDEO', 1, 4);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (10, 'Legislação e obrigações do detentor de registro', 22, 'LEITURA', 2, 4);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (11, 'Glossário essencial de farmacovigilância', 14, 'LEITURA', 3, 4);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (5, 'Notificação e análise de causalidade', 2, 2);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (12, 'Prazos de notificação e elementos mínimos', 18, 'VIDEO', 1, 5);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (13, 'Algoritmo de causalidade na prática', 26, 'VIDEO', 2, 5);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (14, 'Avaliação do módulo de notificação', 12, 'QUIZ', 3, 5);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (3, 'LGPD Aplicada à Indústria Farmacêutica', 'Compliance', 'Dra. Camila Ferrarezi', 'Tratamento de dados pessoais sensíveis em contexto de saúde, bases legais aplicáveis e as regras de anonimização antes do compartilhamento.', 8, true, '2026-10-30');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (6, 'Fundamentos da LGPD', 1, 3);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (15, 'Princípios e agentes de tratamento', 20, 'VIDEO', 1, 6);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (16, 'Bases legais além do consentimento', 22, 'LEITURA', 2, 6);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (17, 'Direitos do titular no dia a dia', 16, 'VIDEO', 3, 6);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (7, 'Dados sensíveis de saúde', 2, 3);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (18, 'Dados de saúde e o risco reputacional', 18, 'VIDEO', 1, 7);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (19, 'Anonimização e pseudonimização na prática', 24, 'LEITURA', 2, 7);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (20, 'Avaliação do módulo de dados sensíveis', 10, 'QUIZ', 3, 7);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (4, 'Segurança do Trabalho em Ambiente Fabril', 'Segurança', 'Eng. Paulo Nakamura', 'Prevenção de acidentes na área produtiva, uso correto de EPIs, resposta a emergências químicas e ergonomia aplicada às linhas de envase.', 14, true, '2027-02-20');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (8, 'Riscos e EPIs', 1, 4);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (21, 'Mapa de riscos da área produtiva', 20, 'VIDEO', 1, 8);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (22, 'Seleção e conservação de EPIs', 18, 'VIDEO', 2, 8);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (23, 'Inspeção de segurança do posto de trabalho', 15, 'LEITURA', 3, 8);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (9, 'Emergências químicas', 2, 4);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (24, 'Fichas de emergência e rotas de fuga', 22, 'VIDEO', 1, 9);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (25, 'Contenção de derramamento de solventes', 25, 'VIDEO', 2, 9);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (26, 'Avaliação do módulo de emergências', 12, 'QUIZ', 3, 9);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (10, 'Ergonomia na produção', 3, 4);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (27, 'Postura e movimentos repetitivos no envase', 20, 'LEITURA', 1, 10);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (28, 'Ginástica laboral e pausas programadas', 16, 'VIDEO', 2, 10);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (5, 'Validação de Processos Produtivos', 'Qualidade', 'Dra. Beatriz Andrade', 'Ciclo de vida da validação, elaboração de protocolos com critérios de aceitação numéricos e a verificação continuada do processo em rotina.', 20, true, '2027-01-31');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (11, 'Ciclo de vida da validação', 1, 5);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (29, 'Desenho, qualificação e verificação continuada', 26, 'VIDEO', 1, 11);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (30, 'Atributos críticos de qualidade', 22, 'LEITURA', 2, 11);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (31, 'Análise de risco aplicada ao processo', 24, 'VIDEO', 3, 11);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (12, 'Protocolos e critérios', 2, 5);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (32, 'Estrutura de um protocolo de validação', 28, 'LEITURA', 1, 12);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (33, 'Definição de critérios de aceitação', 25, 'VIDEO', 2, 12);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (34, 'Avaliação do módulo de protocolos', 15, 'QUIZ', 3, 12);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (13, 'Verificação continuada', 3, 5);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (35, 'Controle estatístico de processo', 30, 'VIDEO', 1, 13);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (36, 'Tratamento de desvios e investigação', 35, 'AO_VIVO', 2, 13);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (6, 'Comunicação Assertiva com Times', 'Comportamental', 'Renata Siqueira', 'Técnicas de comunicação clara e respeitosa para alinhamento entre áreas, com foco em feedback estruturado e condução de conversas difíceis.', 6, false, NULL);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (14, 'Bases da comunicação assertiva', 1, 6);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (37, 'Escuta ativa e checagem de entendimento', 18, 'VIDEO', 1, 14);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (38, 'Diferença entre assertivo, passivo e agressivo', 15, 'LEITURA', 2, 14);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (39, 'Comunicação em times multidisciplinares', 20, 'VIDEO', 3, 14);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (15, 'Feedback e conversas difíceis', 2, 6);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (40, 'Estrutura de feedback baseado em fatos', 22, 'VIDEO', 1, 15);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (41, 'Como receber feedback sem defensividade', 16, 'LEITURA', 2, 15);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (42, 'Avaliação do módulo de feedback', 10, 'QUIZ', 3, 15);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (7, 'Compliance e Código de Conduta', 'Compliance', 'Dr. Marcelo Bittencourt', 'Código de conduta do Instituto Eurofarma, política de brindes e hospitalidade, conflito de interesses e o funcionamento do canal de denúncias.', 5, true, '2026-09-30');
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (16, 'Código de conduta Eurofarma', 1, 7);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (43, 'Valores e condutas esperadas', 16, 'VIDEO', 1, 16);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (44, 'Política de brindes e hospitalidade', 18, 'LEITURA', 2, 16);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (45, 'Relacionamento com profissionais de saúde', 20, 'VIDEO', 3, 16);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (17, 'Canal de denúncias e conflito de interesses', 2, 7);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (46, 'Como declarar conflito de interesses', 15, 'LEITURA', 1, 17);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (47, 'Avaliação do módulo de compliance', 10, 'QUIZ', 2, 17);

INSERT INTO tb_curso (id, titulo, categoria, instrutor, descricao, carga_horaria, obrigatorio, prazo) VALUES (8, 'Excel Avançado para Análise de Dados', 'Produtividade', 'Fernando Lopes', 'Tabelas dinâmicas, fórmulas de análise e construção de painéis para acompanhamento de indicadores de produção e qualidade.', 16, false, NULL);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (18, 'Tabelas dinâmicas', 1, 8);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (48, 'Estruturando a base para análise', 24, 'VIDEO', 1, 18);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (49, 'Agrupamentos e campos calculados', 26, 'VIDEO', 2, 18);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (50, 'Segmentação e linha do tempo', 20, 'LEITURA', 3, 18);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (19, 'Fórmulas de análise', 2, 8);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (51, 'PROCX e referências dinâmicas', 28, 'VIDEO', 1, 19);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (52, 'Funções condicionais aninhadas', 25, 'VIDEO', 2, 19);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (53, 'Avaliação do módulo de fórmulas', 15, 'QUIZ', 3, 19);
INSERT INTO tb_modulo (id, titulo, ordem, curso_id) VALUES (20, 'Dashboards', 3, 8);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (54, 'Escolha de gráficos por tipo de indicador', 22, 'LEITURA', 1, 20);
INSERT INTO tb_aula (id, titulo, duracao_minutos, tipo, ordem, modulo_id) VALUES (55, 'Montando um painel de produção', 30, 'AO_VIVO', 2, 20);

INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (1, 1, 1, '2026-07-14', '2026-09-02', 0.625, 'MEDIO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (1, 1, 1, '2026-09-02 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (2, 1, 2, '2026-09-02 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (3, 1, 3, '2026-09-02 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (4, 1, 4, '2026-09-02 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (5, 1, 5, '2026-09-02 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (2, 1, 2, '2026-08-01', '2026-08-24', 0.0, 'ALTO');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (3, 1, 3, '2026-05-20', '2026-08-29', 1.0, 'BAIXO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (6, 3, 15, '2026-08-29 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (7, 3, 16, '2026-08-29 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (8, 3, 17, '2026-08-29 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (9, 3, 18, '2026-08-29 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (10, 3, 19, '2026-08-29 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (11, 3, 20, '2026-08-29 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (4, 1, 4, '2026-08-11', '2026-09-01', 0.25, 'MEDIO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (12, 4, 21, '2026-09-01 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (13, 4, 22, '2026-09-01 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (5, 1, 5, '2026-06-30', '2026-08-19', 0.5, 'ALTO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (14, 5, 29, '2026-08-19 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (15, 5, 30, '2026-08-19 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (16, 5, 31, '2026-08-19 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (17, 5, 32, '2026-08-19 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (6, 1, 6, '2026-07-28', '2026-09-04', 0.5, 'BAIXO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (18, 6, 37, '2026-09-04 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (19, 6, 38, '2026-09-04 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (20, 6, 39, '2026-09-04 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (7, 1, 7, '2026-04-15', '2026-07-22', 1.0, 'BAIXO');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (21, 7, 43, '2026-07-22 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (22, 7, 44, '2026-07-22 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (23, 7, 45, '2026-07-22 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (24, 7, 46, '2026-07-22 20:15:00');
INSERT INTO tb_aula_concluida (id, matricula_id, aula_id, data_conclusao) VALUES (25, 7, 47, '2026-07-22 20:15:00');
INSERT INTO tb_matricula (id, usuario_id, curso_id, data_matricula, data_ultimo_acesso, progresso, risco) VALUES (8, 1, 8, '2026-09-01', '2026-09-01', 0.0, 'BAIXO');

INSERT INTO tb_sala_estudo (id, titulo, mediador, horario, descricao, participantes, capacidade, ao_vivo, curso_relacionado_id) VALUES (1, 'Revisão de BPF antes da auditoria', 'Dra. Helena Vasconcelos', 'Hoje, 19h00', 'Encontro de 50 minutos para revisar os pontos críticos de contaminação cruzada antes da auditoria de novembro.', 9, 12, true, 1);
INSERT INTO tb_sala_estudo (id, titulo, mediador, horario, descricao, participantes, capacidade, ao_vivo, curso_relacionado_id) VALUES (2, 'Plantão de dúvidas: protocolos de validação', 'Dra. Beatriz Andrade', 'Hoje, 20h30', 'Sala dedicada a tirar dúvidas sobre critérios de aceitação e tratamento de desvios em protocolos.', 8, 8, false, 5);
INSERT INTO tb_sala_estudo (id, titulo, mediador, horario, descricao, participantes, capacidade, ao_vivo, curso_relacionado_id) VALUES (3, 'Casos reais de evento adverso', 'Dr. Rogério Tanaka', 'Amanhã, 18h00', 'Discussão de três casos anonimizados para praticar o algoritmo de causalidade e os prazos de notificação.', 4, 10, false, 2);
INSERT INTO tb_sala_estudo (id, titulo, mediador, horario, descricao, participantes, capacidade, ao_vivo, curso_relacionado_id) VALUES (4, 'LGPD no dia a dia da Qualidade', 'Dra. Camila Ferrarezi', 'Quinta, 19h30', 'Roda de conversa sobre anonimização de relatos e compartilhamento seguro de dados com parceiros.', 6, 15, false, 3);
INSERT INTO tb_sala_estudo (id, titulo, mediador, horario, descricao, participantes, capacidade, ao_vivo, curso_relacionado_id) VALUES (5, 'Oficina de dashboards de produção', 'Fernando Lopes', 'Sexta, 17h00', 'Sessão prática construindo um painel de indicadores de envase do zero, com dados de exemplo.', 2, 8, false, 8);

INSERT INTO tb_alerta_evasao (id, titulo, descricao, acao_sugerida, nivel, probabilidade, usuario_id, curso_relacionado_id) VALUES (1, 'Ritmo de estudo caiu em Farmacovigilância', 'Você não acessa este curso há 14 dias e o prazo de conclusão termina em 12 dias. Nenhuma das 6 aulas foi concluída até agora.', 'Comece pelo Módulo 1, que leva 20 minutos e destrava as duas aulas seguintes da trilha.', 'ALTO', 78, 1, 2);
INSERT INTO tb_alerta_evasao (id, titulo, descricao, acao_sugerida, nivel, probabilidade, usuario_id, curso_relacionado_id) VALUES (2, 'Progresso parado em Validação de Processos', 'Você concluiu 4 das 8 aulas e não retoma o curso há 19 dias. Colaboradores que param nesse ponto costumam abandonar a trilha.', 'Agende 30 minutos na quinta para a aula de controle estatístico e retome o ritmo antes do prazo de janeiro.', 'MEDIO', 54, 1, 5);

INSERT INTO tb_conquista (id, titulo, descricao, tipo, desbloqueada, usuario_id) VALUES (1, 'Primeira trilha concluída', 'Concluiu a primeira trilha completa da plataforma.', 'Progresso', true, 1);
INSERT INTO tb_conquista (id, titulo, descricao, tipo, desbloqueada, usuario_id) VALUES (2, 'Sequência de 7 dias', 'Estudou por sete dias seguidos sem quebrar a ofensiva.', 'Ofensiva', true, 1);
INSERT INTO tb_conquista (id, titulo, descricao, tipo, desbloqueada, usuario_id) VALUES (3, 'Guardião do compliance', 'Concluiu todos os treinamentos obrigatórios de Compliance no prazo.', 'Regulatório', true, 1);
INSERT INTO tb_conquista (id, titulo, descricao, tipo, desbloqueada, usuario_id) VALUES (4, 'Mestre da EdIA', 'Faça 50 perguntas à EdIA para desbloquear esta conquista.', 'Engajamento', false, 1);

ALTER TABLE tb_usuario ALTER COLUMN id RESTART WITH 2;
ALTER TABLE tb_curso ALTER COLUMN id RESTART WITH 9;
ALTER TABLE tb_modulo ALTER COLUMN id RESTART WITH 21;
ALTER TABLE tb_aula ALTER COLUMN id RESTART WITH 56;
ALTER TABLE tb_matricula ALTER COLUMN id RESTART WITH 9;
ALTER TABLE tb_aula_concluida ALTER COLUMN id RESTART WITH 26;
ALTER TABLE tb_sala_estudo ALTER COLUMN id RESTART WITH 6;
ALTER TABLE tb_alerta_evasao ALTER COLUMN id RESTART WITH 3;
ALTER TABLE tb_conquista ALTER COLUMN id RESTART WITH 5;
ALTER TABLE tb_mensagem_edia ALTER COLUMN id RESTART WITH 1;
